spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: cursoms-eureka-pass

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://cursoms-eureka-user:cursoms-eureka-pass@${EUREKA_SERVER}:8761/eureka