spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: cursoms-eureka-pass

server:
  port: 8761


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false